# Generated by Django 6.0.2 on 2026-03-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_firstname_user_gender_user_lastname_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('journalist', 'Journalist'), ('advertiser', 'Advertiser'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
